branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"
before_install:
   - bash /bin/echo before_install
before_script:
   - bash "echo before_script"
after_script:
   - bash "echo after_script"
after_failure:
   - bash echo "after failure"
   #- bash cat /home/travis/.cpanm/work/*/build.log
